web:
  restart: always
  build: ./web
  expose:
    - "4041"
  links:
    - db
  volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro   
  command: /usr/local/bin/gunicorn -w 2 -b :4041 server:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "4040:80"
  volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro     
  volumes_from:
    - web
  links:
    - web:web

db:
  image: mongo:latest    
  volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro     
